apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-demo-news
  labels:
    app.kubernetes.io/name: llm-demo-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llm-demo-news
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llm-demo-news
    spec:
      containers:
        - name: llm-demo-news
          image: "us-docker.pkg.dev/castai-hub/library/llm-demo-news:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: llm-demo-news
  labels:
    app.kubernetes.io/name: llm-demo-news
spec:
  selector:
    app.kubernetes.io/name: llm-demo-news
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
